services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../app/public:/var/www/html
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - portfolio-net

  php:
    build: ./services/php
    container_name: php
    volumes:
      - ../app/public:/var/www/html
      - ../app/includes:/var/www/html/includes
      - ../app/css:/var/www/html/css
      - ../app/js:/var/www/html/js
    networks:
      - portfolio-net

  adminer:
    image: adminer:latest
    ports:
      - "3000:3000"
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
